//initial store

export default {
  users: [
    {
      username: "user",
      password: "password",
    },
    {
      username: "admin",
      password: "password",
    },
  ],
  drivers: [
    {
      id: 1,
      username: "John Doe",
      distance: "6 mins away",
      rating: "4.5",
      route: ["koramangla", "whitefield"],
      car: "Polo",
      seats: 1,
      lat: 12.897952,
      lng: 77.581265,
    },
    {
      id: 2,
      username: "John Doe",
      distance: "6 mins away",
      rating: "4.5",
      route: ["sector 49", "whitefield"],
      car: "Polo",
      seats: 3,
      lat: 12.94913,
      lng: 77.663213,
    },
    {
      id: 3,
      username: "John Doe",
      distance: "6 mins away",
      rating: "4.5",
      route: ["koramangla", "sector 49"],
      car: "Polo",
      seats: 3,
      lat: 12.982431,
      lng: 77.664922,
    },
    {
      id: 4,
      username: "John Doe",
      distance: "6 mins away",
      rating: "4.5",
      route: ["Jayanagar", "koramangla"],
      car: "Polo",
      seats: 3,
      lat: 12.887278,
      lng: 77.650339,
    },
    {
      id: 5,
      username: "John Doe",
      distance: "6 mins away",
      rating: "4.5",
      route: ["sector 49", "Jayanagar"],
      car: "Polo",
      seats: 3,
      lat: 12.827278,
      lng: 77.650339,
    },
    {
      id: 6,
      username: "John Doe",
      distance: "6 mins away",
      rating: "4.5",
      route: ["Uttarahalli", "Kumaraswamy"],
      car: "Polo",
      seats: 3,
      lat: 12.817278,
      lng: 77.650339,
    },
  ],
}
